DROP TABLE IF EXISTS Characteristics;
DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS Delivery;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Phone;

CREATE TABLE phone (
ID INT(10) NOT NULL AUTO_INCREMENT,
COMPANY VARCHAR(20) NOT NULL,
MODEL VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE characteristics (
ID INT(10) NOT NULL AUTO_INCREMENT,
BODY VARCHAR(20) NOT NULL,
COLOR VARCHAR(20) NOT NULL,
SCREEN_SIZE INT(5) NOT NULL,
PRIMARY KEY (`ID`),
FOREIGN KEY (ID) REFERENCES phone(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE company (
COMPANY_ID INT(10) NOT NULL AUTO_INCREMENT,
PHONE_ID INT(10) NOT NULL,
NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (`COMPANY_ID`),
FOREIGN KEY (PHONE_ID) REFERENCES phone(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE clients (
ORDER_ID INT(10) NOT NULL AUTO_INCREMENT,
PHONE_ID INT(10) NOT NULL,
COMMENTS VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,
AMOUNT INT(5) NOT NULL,
PRIMARY KEY (`ORDER_ID`),
FOREIGN KEY (PHONE_ID) REFERENCES phone(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE delivery (
ORDER_ID INT(10) NOT NULL AUTO_INCREMENT,
TYPE VARCHAR(20) NOT NULL,
PRIMARY KEY (`ORDER_ID`),
FOREIGN KEY (ORDER_ID) REFERENCES clients(ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
